import = [
  #  "~/.config/alacritty/themes/github_light_high_contrast.toml",
"~/.config/alacritty/themes/catppuccin-mocha.toml",
]
[font.normal]
family = "JetBrainsMono Nerd Font"
[env]
TERM = "xterm-256color"
